{% set name = "bravado-core" %}
{% set version = "5.16.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2681d179d3b6baca3f34f43cd3c5af34f9b776328b6ed437b10ae8e3e2f8ced

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - jsonref
    - jsonschema[format] >=2.5.1
    - msgpack-python
    - pip
    - python
    - python-dateutil
    - pytz
    - pyyaml
    - simplejson
    - six
    - swagger-spec-validator >=2.0.1
  run:
    - jsonref
    - jsonschema[format] >=2.5.1
    - msgpack-python
    - python
    - python-dateutil
    - pytz
    - pyyaml
    - simplejson
    - six
    - swagger-spec-validator >=2.0.1

test:
  imports:
    - bravado_core

about:
  home: https://github.com/Yelp/bravado-core
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library for adding Swagger support to clients and servers

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
